### ISSUE TITLE
2.0 Branch - Error Type: <type 'exceptions.NameError'>  Error Contents: global name 'ddDir' is not defined

### ISSUE THREAD

**Issue by xekon** [ampache/ampache-xbmc-plugin#14]
ampache plugin latest 2.0: https://github.com/ampache/ampache-xbmc-plugin/commit/82da0532e03c9261404f41d6123e15b8d16ee438

Ampache Server 4.4.0 : https://github.com/ampache/ampache/tree/master

Kodi 18.9  (2:18.9+git20201024.0821-final-0focal)

Kodi Log when I try to Access Library view of the Ampache plugin:
```
2021-02-19 09:44:48.188 T:140499233392384   ERROR: GetDirectory - Error getting plugin://plugin.audio.ampache/?mode=51&submode=None
2021-02-19 09:44:48.196 T:140500941810368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.ampache/?mode=51&submode=None) failed
2021-02-19 09:45:13.581 T:140499233392384   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'ddDir' is not defined
                                            Traceback (most recent call last):
                                              File "/home/jieiku/.kodi/addons/plugin.audio.ampache/default.py", line 4, in <module>
                                                Main()
                                              File "/home/jieiku/.kodi/addons/plugin.audio.ampache/resources/lib/ampache_plugin.py", line 873, in Main
                                                ddDir(ut.tString(30226) + " (" + ampache.getSetting("podcasts")+ ")",5,5)
                                            NameError: global name 'ddDir' is not defined
                                            -->End of Python script error report<--
2021-02-19 09:45:13.613 T:140499224999680   ERROR: GetDirectory - Error getting plugin://plugin.audio.ampache/?mode=51&submode=None
2021-02-19 09:45:13.616 T:140500941810368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.ampache/?mode=51&submode=None) failed
```

When I select "Library..." I get the error:

![2021-02-19_09-45](https://user-images.githubusercontent.com/106644/108541745-ae031d80-7297-11eb-91e9-b4978f3aa87b.png)

**Comment by lusum** [comment]
Was a typo ( ddDir instead of addDir ), fixed
