### ISSUE TITLE
Problem with version 2 with my kodi 19 !

### ISSUE THREAD

**Issue by jylenhof** [ampache/ampache-xbmc-plugin#18]
2021-03-21 18:28:38.502 T:4957     INFO <general>: initializing python engine.
2021-03-21 18:30:16.106 T:1725     INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-03-21 18:30:16.141 T:1725     INFO <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms Periodsize 50 ms
2021-03-21 18:31:46.708 T:4957    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '<' not supported between instances of 'int' and 'str'
                                                   Traceback (most recent call last):
                                                     File "/home/invite/.kodi/addons/plugin.audio.ampache/default.py", line 4, in <module>
                                                       Main()
                                                     File "/home/invite/.kodi/addons/plugin.audio.ampache/resources/lib/ampache_plugin.py", line 1030, in Main
                                                       if servers_manager.addServer():
                                                     File "/home/invite/.kodi/addons/plugin.audio.ampache/resources/lib/servers_manager.py", line 140, in addServer
                                                       jsStorServer.save(serverData)
                                                     File "/home/invite/.kodi/addons/plugin.audio.ampache/resources/lib/json_storage.py", line 34, in save
                                                       json.dump(self._data, fd, indent=4, sort_keys=True)
                                                     File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
                                                       for chunk in iterable:
                                                     File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
                                                       yield from _iterencode_dict(o, _current_indent_level)
                                                     File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
                                                       yield from chunks
                                                     File "/usr/lib/python3.7/json/encoder.py", line 353, in _iterencode_dict
                                                       items = sorted(dct.items(), key=lambda kv: kv[0])
                                                   TypeError: '<' not supported between instances of 'int' and 'str'
                                                   -->End of Python script error report<--
                                                   
2021-03-21 18:31:47.006 T:4957  WARNING <general>: CPythonInvoker(83, /home/invite/.kodi/addons/plugin.audio.ampache/default.py): the python script "/home/invite/.kodi/addons/plugin.audio.ampache/default.py" has
 left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-03-21 18:31:47.006 T:4957     INFO <general>: Python interpreter stopped

**Comment by lusum** [comment]
It seems a problem with the server data..  I would need the server data that causes this problem to handle it.

**Comment by lusum** [comment]
Fixed in master
