### ISSUE TITLE
Unable to find songs on Nextcloud music

### ISSUE THREAD

**Issue by GTP95** [ampache/ampache-xbmc-plugin#25]
Greetings,

I just installed apache from kodi's repos, but after configuring it to connect to my Nextcloud server (specifically to Nextcloud's Music app) it doesn't seem to find any song/album (browsing inside those categories just returns empty lists) and when going into the "random" section if I try to go into "Random Songs" an error happens. By looking at the logs, this seems to be the error related to getting random songs:
```
2022-09-11 20:56:15.608 T:1784    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: invalid literal for int() with base 10: ''
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.audio.ampache/default.py", line 4, in <module>
                                                       Main()
                                                     File "/storage/.kodi/addons/plugin.audio.ampache/resources/lib/ampache_plugin.py", line 827, in Main
                                                       manage_stats_menu("songs",submode)
                                                     File "/storage/.kodi/addons/plugin.audio.ampache/resources/lib/ampache_plugin.py", line 688, in manage_stats_menu
                                                       get_random(object_type, num_items)
                                                     File "/storage/.kodi/addons/plugin.audio.ampache/resources/lib/ampache_plugin.py", line 584, in get_random
                                                       tot_items = int(ampache.getSetting(object_type))
                                                   ValueError: invalid literal for int() with base 10: ''
                                                   -->End of Python script error report<--
```
While instead, the section about browsing the other categories doesn't seem to tell much:
```
2022-09-11 21:09:21.544 T:2220    DEBUG <CAddonSettings[plugin.audio.ampache]>: trying to load setting definitions from old format...
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (add) was not found.
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (albums) was not found.
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (artists) was not found.
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (live_streams) was not found.
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (playlists) was not found.
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (podcasts) was not found.
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (session_expire) was not found.
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (songs) was not found.
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (token) was not found.
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (token-exp) was not found.
2022-09-11 21:09:21.546 T:2220    DEBUG <CSettingsManager>: requested setting (videos) was not found.
```
You can see [here](http://ix.io/4afi) the full logs. Am I doing something wrong or is this a bug?
Thank you for your help,

GTP

**Comment by lusum** [comment]
>https://nas.gtpware.eu/nextcloud/index.php/apps/music/ampache/server/xml.server.php/server/xml.server.php?action=handshake&auth=dcf6fa580b93ab12b701145c334c620792e1d5d136e6f81d0a992b560dfa81c5&timestamp=1662930561&version=590001&user=giacomo

It seems a problem in the url you send to the server, the url in the configuration should be 

>https://nas.gtpware.eu/nextcloud/index.php/apps/music/ampache/

server/xml.server .... is added by the plugin, if you see your connection string this is added twice

**Comment by GTP95** [comment]
I've already tried with `https://nas.gtpware.eu/nextcloud/index.php/apps/music/ampache/`, the problem is that in this case I get a connection error, while with the longer version I wasn't getting any error in the settings page so I assumed that it was correct... I'll now check the logs to see if the connection error is due to wrong credentials or something else.

**Comment by GTP95** [comment]
By searching for the string `connection` in the logs I didn't find anything relevant, does the reason for the failed connection get logged? Here are the [new logs](http://ix.io/4ak9).

**Comment by lusum** [comment]
>2022-09-11 21:09:22.398 T:2220    DEBUG <general>: AmpachePlugin::AMPACHECONNECT: contents <!DOCTYPE html>
                                                   <html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" >

Nextcloud server send in both cases an html error page, so this is a connection error. I don't know the reason.

**Comment by GTP95** [comment]
Fixed, I had to generate a password from the Music app's interface instead of from Nextcloud's settings.
